[package]
name = "day-8"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "day-8"
path = "benches/benchmarks.rs"

[dependencies]
dhat = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
dhat-heap = []
