
solve day part:
    cargo run --package {{day}} --bin {{part}}

test:
    cargo nextest run

bench day part:
    cargo bench --bench {{day}} {{part}} >> tmp/benches/{{day}}{{part}}.bench.txt

dhat day part:
    cargo run --profile dhat --features dhat-heap --package {{day}} --bin {{part}}

flamegraph day part:
    cargo flamegraph --profile flamegraph --root --package {{day}} --bin {{part}} -o tmp/flamegraphs/{{day}}--{{part}}.svg

create day:
    cargo generate --path ./daily-template --name {{day}}
